remote:
     user: russell
     password: nails income laid fairly
     host: joshuacook.me
     dbname: project_6
     port : 5432

remote_dev:
     user: russell
     password: nails income laid fairly
     host: joshuacook.me
     dbname: project_6_dev
     port : 5432


local: 
     user: russell
     password: nails income laid fairly
     host: localhost
     dbname: Project6
     port : 5432